defaults:
  - trainer: base
  - _self_
  - data: cifar10
  - optim: sgd_fixmatch
  - model: resnet_fixmatch
  - sem_sl : fixmatch
  - query: entropy
  - active: standard

trainer:
  batch_size: 64
  num_workers: 10
  max_epochs: 200
  min_epochs: 50
  experiment_name: test_fixmatch
  train_iters_per_epoch: 1000
  load_best_ckpt: False
  save_last: True

hydra:
  run:
    dir: ${trainer.experiments_root}/${trainer.experiment_name}/${trainer.experiment_id}
