name: bayesian_wide_resnet
model_width: 8
model_depth: 28
weight_decay: 0.001  
learning_rate: 0.03
dropout_p: 0
load_pretrained: Null
freeze_encoder: False
use_ema: True
exclude_bn_bias: True
k: 50
finetune: False
small_head: True